development:
  adapter: postgresql
  encoding: unicode
  database: carpediem_dev
  pool: 5
  username: carpediem
  password: hekpCD472472
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: carpediem_test
  pool: 5
  username: carpediem
  password: hekpCD472472
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: carpediem
  pool: 5
  username: carpediem
  password: hekpCD472472
  timeout: 5000
